#[env]
#TERM = "xterm-256color"
#COLORTERM = "truecolor"
#LANG = "en_US.UTF-8"

[font]
size = 15

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

#[window]
#decorations = "None"
#dynamic_padding = true
#opacity = 1
#startup_mode = "Maximized"

[window.padding]
x = 15
y = 15

#[terminal.shell]
#program = "wsl"
#args = [
#    "-d",
#    "Debian",
#    "--cd",
#    "~"
#]
